title: Muhammet Abdullah Şahin
email: hello@ahmetyilmaz.dev
description: >- # this means to ignore newlines until "baseurl:"
  Ahmet Yılmaz'ın Full Stack Developer ve UI/UX Designer olarak projelerini
  ve deneyimlerini içeren kişisel portfolyo sitesi.
baseurl: "/portfolio" # Depo adınız, eğer site "kullaniciadi.github.io/depo-adi/" altında ise "/depo-adi"
url: "https://sahinmuhammetabdullah.github.io" # GitHub Pages ana URL'niz
github_username:  kullaniciadi # GitHub kullanıcı adınız

# Build settings
markdown: kramdown
theme: null # Kendi temamızı kullanıyoruz
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot

# Collections (Projeler için)
collections:
  projects:
    output: false # Projeler için ayrı sayfa oluşturmayacağız, modal kullanacağız
    # Eğer ayrı proje sayfaları isterseniz true yapın ve permalink ekleyin

# Jekyll Polyglot Ayarları
languages: ["tr", "en"]
default_lang: "tr"
exclude_from_localization: ["assets/", "admin/"] # Çevrilmeyecek dosyalar/klasörler
parallel_localization: false # Hata ayıklama için false, performans için true
default_lang_in_url: false   # YENİ EKLENEN SATIR


# Sass ayarları (Eğer SASS kullanacaksanız)
# sass:
#   sass_dir: _sass
#   style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .github
  - .vscode
  