email: m.sahinabdullah@gmail.com
title: Muhammet Abdullah Şahin
author: Muhammet Abdullah Şahin # Veya sitenin genel sahibi
description: >-
  Muhammet Abdullah Şahin'in Full Stack Developer ve UI/UX Designer olarak projelerini
  ve deneyimlerini içeren kişisel portfolyo sitesi.

baseurl: "/portfolio"
url: "https://sahinmuhammetabdullah.github.io"

github_username:  SahinMuhammetAbdullah # GitHub kullanıcı adınız

# Build settings
markdown: kramdown
theme: null # Kendi temamızı kullanıyoruz
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot

# Collections (Projeler için)
collections:
  projects:
    output: false # Projeler için ayrı sayfa oluşturmayacağız, modal kullanacağız
    # Eğer ayrı proje sayfaları isterseniz true yapın ve permalink ekleyin

# Jekyll Polyglot Ayarları
languages: ["tr", "en"]
default_lang: "tr"
exclude_from_localization: ["assets/", "admin/"] # Çevrilmeyecek dosyalar/klasörler
parallel_localization: false # Hata ayıklama için false, performans için true
default_lang_in_url: false   # YENİ EKLENEN SATIR


# Sass ayarları (Eğer SASS kullanacaksanız)
# sass:
#   sass_dir: _sass
#   style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .github
  - .vscode
  
theme_color: "#1e1e2e"       # PWA ve tarayıcı UI için ana tema rengi (Catppuccin Base)
background_color: "#11111b"  # PWA splash screen için arka plan rengi (Catppuccin Crust)
ms_tile_color: "#b4befe"     # Windows Metro karo rengi (Catppuccin Lavender)
favicon: /assets/images/favicon/favicon-96x96.png

technologies_used:
  - name: "Jekyll"
    url: "https://jekyllrb.com/"
  - name: "Tailwind CSS"
    url: "https://tailwindcss.com/"
  - name: "Font Awesome"
    url: "https://fontawesome.com/"
  - name: "Catppuccin Theme"
    url: "https://github.com/catppuccin/catppuccin"

license_name: "MIT License" # Kullandığınız lisansın adı
license_url: "https://opensource.org/licenses/MIT" # Lisans metnine link (veya projenizdeki LISENCE dosyasına)
repository_url: "https://github.com/SahinMuhammetAbdullah/portfolio" # Projenizin GitHub depo URL'si
designer_name: "Muhammet Abdullah Şahin"
designer_url: "https://sahinmuhammetabdullah.github.io/portfolio/" # Tasarımcının web sitesi veya portfolyosu