name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # Veya sitenizin ana dalı (master, main vb.)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # GitHub Pages'a yazma izni vermek için
    permissions:
      contents: read
      pages: write
      id-token: write
    # GitHub Pages'a deploy için ortam ayarı
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Gemfile'ınızla uyumlu Ruby sürümü
          bundler-cache: true # 'bundle install' çalıştırır ve gem'leri önbelleğe alır

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        # Kendi Gemfile'ınızdaki Jekyll ve eklentileri kullanır
        # Baseurl'i GitHub Pages ortam değişkeninden alır
        run: bundle exec jekyll build --destination ./_site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        # Jekyll build çıktısını GitHub Pages'a yükler
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # Bu adım, 'Upload artifact' adımından gelen çıktıyı alır ve deploy eder