name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Veya sitenizin ana dalı (master vb.)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Depoyu okuma izni
      pages: write    # GitHub Pages'a yazma izni
      id-token: write # GitHub Pages deploy için gerekli

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Gemfile'ınızdaki veya projenizin gerektirdiği Ruby sürümü
          bundler-cache: true # Gemfile.lock'a göre 'bundle install' çalıştırır ve gem'leri önbelleğe alır

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v4
        # Bu adım, GitHub Pages için baseurl gibi ortam değişkenlerini ayarlar

      - name: Build Jekyll site
        # Kendi Gemfile'ınızdaki Jekyll ve eklentileri (jekyll-polyglot dahil) kullanarak build eder.
        # Baseurl, bir önceki 'Setup GitHub Pages' adımından alınır.
        run: bundle exec jekyll build --destination ./_site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production # Üretim ortamı için build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # Build edilen _site klasörünü yükle

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # Yüklenen artifact'i GitHub Pages'a deploy eder