name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Veya sitenizin ana dalı (master, main vb.)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Jekyll ve eklentilerinizle uyumlu Ruby sürümü
          bundler-cache: true # bundle install'ı hızlandırır

      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # Eğer özel bir domain kullanıyorsanız:
          # cname: yourdomain.com